version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shift_management_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./shifts.db
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data  # Persistent data storage
      - ./logs:/app/logs  # Application logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shift_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: shift_management_frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shift_network

  nginx:
    image: nginx:alpine
    container_name: shift_management_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - shift_network

networks:
  shift_network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local
